from .credentials import TELEGRAM_TOKEN, SESSION_BACKEND_HOST
from .messages import (
    HELP_CMD, START_CMD, EXAM_INFO, NOT_EXAMS,
    EXAMS_ARE_EXIST, EXAM_NUMBER, SEVER_RESPONSE_MESSAGE, SERVER_INTERNAL_ERROR
)
from .statuses import HTTP_200_OK, HTTP_400_BAD_REQUEST, HTTP_500_INTERNAL_ERROR
