name: CI/CD

on:
  push:
    branches:
      - dev


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: generate envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_TELEGRAM_TOKEN: ${{ secrets.TELOXIDE_TOKEN }}
          directory: ./
          file_name: .env
          fail_on_empty: true

      - name: login in server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "./"
          target: "~/mysibsau-session-telegram-bot"

      - name: launch bot
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd mysibsau-session-telegram-bot
            make reload